
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrderData` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model OrderData
 * 
 */
export type OrderDataModel = runtime.Types.Result.DefaultSelection<Prisma.$OrderDataPayload>

export type AggregateOrderData = {
  _count: OrderDataCountAggregateOutputType | null
  _avg: OrderDataAvgAggregateOutputType | null
  _sum: OrderDataSumAggregateOutputType | null
  _min: OrderDataMinAggregateOutputType | null
  _max: OrderDataMaxAggregateOutputType | null
}

export type OrderDataAvgAggregateOutputType = {
  id: number | null
  total: number | null
}

export type OrderDataSumAggregateOutputType = {
  id: number | null
  total: number | null
}

export type OrderDataMinAggregateOutputType = {
  id: number | null
  date: Date | null
  total: number | null
}

export type OrderDataMaxAggregateOutputType = {
  id: number | null
  date: Date | null
  total: number | null
}

export type OrderDataCountAggregateOutputType = {
  id: number
  date: number
  total: number
  data: number
  _all: number
}


export type OrderDataAvgAggregateInputType = {
  id?: true
  total?: true
}

export type OrderDataSumAggregateInputType = {
  id?: true
  total?: true
}

export type OrderDataMinAggregateInputType = {
  id?: true
  date?: true
  total?: true
}

export type OrderDataMaxAggregateInputType = {
  id?: true
  date?: true
  total?: true
}

export type OrderDataCountAggregateInputType = {
  id?: true
  date?: true
  total?: true
  data?: true
  _all?: true
}

export type OrderDataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrderData to aggregate.
   */
  where?: Prisma.OrderDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderData to fetch.
   */
  orderBy?: Prisma.OrderDataOrderByWithRelationInput | Prisma.OrderDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrderDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrderData
  **/
  _count?: true | OrderDataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrderDataAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrderDataSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrderDataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrderDataMaxAggregateInputType
}

export type GetOrderDataAggregateType<T extends OrderDataAggregateArgs> = {
      [P in keyof T & keyof AggregateOrderData]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrderData[P]>
    : Prisma.GetScalarType<T[P], AggregateOrderData[P]>
}




export type OrderDataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderDataWhereInput
  orderBy?: Prisma.OrderDataOrderByWithAggregationInput | Prisma.OrderDataOrderByWithAggregationInput[]
  by: Prisma.OrderDataScalarFieldEnum[] | Prisma.OrderDataScalarFieldEnum
  having?: Prisma.OrderDataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrderDataCountAggregateInputType | true
  _avg?: OrderDataAvgAggregateInputType
  _sum?: OrderDataSumAggregateInputType
  _min?: OrderDataMinAggregateInputType
  _max?: OrderDataMaxAggregateInputType
}

export type OrderDataGroupByOutputType = {
  id: number
  date: Date
  total: number
  data: runtime.JsonValue
  _count: OrderDataCountAggregateOutputType | null
  _avg: OrderDataAvgAggregateOutputType | null
  _sum: OrderDataSumAggregateOutputType | null
  _min: OrderDataMinAggregateOutputType | null
  _max: OrderDataMaxAggregateOutputType | null
}

type GetOrderDataGroupByPayload<T extends OrderDataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrderDataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrderDataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrderDataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrderDataGroupByOutputType[P]>
      }
    >
  >



export type OrderDataWhereInput = {
  AND?: Prisma.OrderDataWhereInput | Prisma.OrderDataWhereInput[]
  OR?: Prisma.OrderDataWhereInput[]
  NOT?: Prisma.OrderDataWhereInput | Prisma.OrderDataWhereInput[]
  id?: Prisma.IntFilter<"OrderData"> | number
  date?: Prisma.DateTimeFilter<"OrderData"> | Date | string
  total?: Prisma.IntFilter<"OrderData"> | number
  data?: Prisma.JsonFilter<"OrderData">
}

export type OrderDataOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  total?: Prisma.SortOrder
  data?: Prisma.SortOrder
}

export type OrderDataWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.OrderDataWhereInput | Prisma.OrderDataWhereInput[]
  OR?: Prisma.OrderDataWhereInput[]
  NOT?: Prisma.OrderDataWhereInput | Prisma.OrderDataWhereInput[]
  date?: Prisma.DateTimeFilter<"OrderData"> | Date | string
  total?: Prisma.IntFilter<"OrderData"> | number
  data?: Prisma.JsonFilter<"OrderData">
}, "id">

export type OrderDataOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  total?: Prisma.SortOrder
  data?: Prisma.SortOrder
  _count?: Prisma.OrderDataCountOrderByAggregateInput
  _avg?: Prisma.OrderDataAvgOrderByAggregateInput
  _max?: Prisma.OrderDataMaxOrderByAggregateInput
  _min?: Prisma.OrderDataMinOrderByAggregateInput
  _sum?: Prisma.OrderDataSumOrderByAggregateInput
}

export type OrderDataScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrderDataScalarWhereWithAggregatesInput | Prisma.OrderDataScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrderDataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrderDataScalarWhereWithAggregatesInput | Prisma.OrderDataScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"OrderData"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"OrderData"> | Date | string
  total?: Prisma.IntWithAggregatesFilter<"OrderData"> | number
  data?: Prisma.JsonWithAggregatesFilter<"OrderData">
}

export type OrderDataCreateInput = {
  date?: Date | string
  total: number
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type OrderDataUncheckedCreateInput = {
  id?: number
  date?: Date | string
  total: number
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type OrderDataUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  total?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type OrderDataUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  total?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type OrderDataCreateManyInput = {
  id?: number
  date?: Date | string
  total: number
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type OrderDataUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  total?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type OrderDataUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  total?: Prisma.IntFieldUpdateOperationsInput | number
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type OrderDataCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  total?: Prisma.SortOrder
  data?: Prisma.SortOrder
}

export type OrderDataAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  total?: Prisma.SortOrder
}

export type OrderDataMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  total?: Prisma.SortOrder
}

export type OrderDataMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  total?: Prisma.SortOrder
}

export type OrderDataSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  total?: Prisma.SortOrder
}



export type OrderDataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  total?: boolean
  data?: boolean
}, ExtArgs["result"]["orderData"]>

export type OrderDataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  total?: boolean
  data?: boolean
}, ExtArgs["result"]["orderData"]>

export type OrderDataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  total?: boolean
  data?: boolean
}, ExtArgs["result"]["orderData"]>

export type OrderDataSelectScalar = {
  id?: boolean
  date?: boolean
  total?: boolean
  data?: boolean
}

export type OrderDataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "total" | "data", ExtArgs["result"]["orderData"]>

export type $OrderDataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrderData"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    date: Date
    total: number
    data: runtime.JsonValue
  }, ExtArgs["result"]["orderData"]>
  composites: {}
}

export type OrderDataGetPayload<S extends boolean | null | undefined | OrderDataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrderDataPayload, S>

export type OrderDataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrderDataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrderDataCountAggregateInputType | true
  }

export interface OrderDataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrderData'], meta: { name: 'OrderData' } }
  /**
   * Find zero or one OrderData that matches the filter.
   * @param {OrderDataFindUniqueArgs} args - Arguments to find a OrderData
   * @example
   * // Get one OrderData
   * const orderData = await prisma.orderData.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrderDataFindUniqueArgs>(args: Prisma.SelectSubset<T, OrderDataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrderDataClient<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrderData that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrderDataFindUniqueOrThrowArgs} args - Arguments to find a OrderData
   * @example
   * // Get one OrderData
   * const orderData = await prisma.orderData.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrderDataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrderDataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderDataClient<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderDataFindFirstArgs} args - Arguments to find a OrderData
   * @example
   * // Get one OrderData
   * const orderData = await prisma.orderData.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrderDataFindFirstArgs>(args?: Prisma.SelectSubset<T, OrderDataFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrderDataClient<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderData that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderDataFindFirstOrThrowArgs} args - Arguments to find a OrderData
   * @example
   * // Get one OrderData
   * const orderData = await prisma.orderData.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrderDataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrderDataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderDataClient<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrderData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderDataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrderData
   * const orderData = await prisma.orderData.findMany()
   * 
   * // Get first 10 OrderData
   * const orderData = await prisma.orderData.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orderDataWithIdOnly = await prisma.orderData.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrderDataFindManyArgs>(args?: Prisma.SelectSubset<T, OrderDataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrderData.
   * @param {OrderDataCreateArgs} args - Arguments to create a OrderData.
   * @example
   * // Create one OrderData
   * const OrderData = await prisma.orderData.create({
   *   data: {
   *     // ... data to create a OrderData
   *   }
   * })
   * 
   */
  create<T extends OrderDataCreateArgs>(args: Prisma.SelectSubset<T, OrderDataCreateArgs<ExtArgs>>): Prisma.Prisma__OrderDataClient<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrderData.
   * @param {OrderDataCreateManyArgs} args - Arguments to create many OrderData.
   * @example
   * // Create many OrderData
   * const orderData = await prisma.orderData.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrderDataCreateManyArgs>(args?: Prisma.SelectSubset<T, OrderDataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OrderData and returns the data saved in the database.
   * @param {OrderDataCreateManyAndReturnArgs} args - Arguments to create many OrderData.
   * @example
   * // Create many OrderData
   * const orderData = await prisma.orderData.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OrderData and only return the `id`
   * const orderDataWithIdOnly = await prisma.orderData.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrderDataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrderDataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OrderData.
   * @param {OrderDataDeleteArgs} args - Arguments to delete one OrderData.
   * @example
   * // Delete one OrderData
   * const OrderData = await prisma.orderData.delete({
   *   where: {
   *     // ... filter to delete one OrderData
   *   }
   * })
   * 
   */
  delete<T extends OrderDataDeleteArgs>(args: Prisma.SelectSubset<T, OrderDataDeleteArgs<ExtArgs>>): Prisma.Prisma__OrderDataClient<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrderData.
   * @param {OrderDataUpdateArgs} args - Arguments to update one OrderData.
   * @example
   * // Update one OrderData
   * const orderData = await prisma.orderData.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrderDataUpdateArgs>(args: Prisma.SelectSubset<T, OrderDataUpdateArgs<ExtArgs>>): Prisma.Prisma__OrderDataClient<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrderData.
   * @param {OrderDataDeleteManyArgs} args - Arguments to filter OrderData to delete.
   * @example
   * // Delete a few OrderData
   * const { count } = await prisma.orderData.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrderDataDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrderDataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrderData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderDataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrderData
   * const orderData = await prisma.orderData.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrderDataUpdateManyArgs>(args: Prisma.SelectSubset<T, OrderDataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrderData and returns the data updated in the database.
   * @param {OrderDataUpdateManyAndReturnArgs} args - Arguments to update many OrderData.
   * @example
   * // Update many OrderData
   * const orderData = await prisma.orderData.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OrderData and only return the `id`
   * const orderDataWithIdOnly = await prisma.orderData.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrderDataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrderDataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OrderData.
   * @param {OrderDataUpsertArgs} args - Arguments to update or create a OrderData.
   * @example
   * // Update or create a OrderData
   * const orderData = await prisma.orderData.upsert({
   *   create: {
   *     // ... data to create a OrderData
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrderData we want to update
   *   }
   * })
   */
  upsert<T extends OrderDataUpsertArgs>(args: Prisma.SelectSubset<T, OrderDataUpsertArgs<ExtArgs>>): Prisma.Prisma__OrderDataClient<runtime.Types.Result.GetResult<Prisma.$OrderDataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrderData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderDataCountArgs} args - Arguments to filter OrderData to count.
   * @example
   * // Count the number of OrderData
   * const count = await prisma.orderData.count({
   *   where: {
   *     // ... the filter for the OrderData we want to count
   *   }
   * })
  **/
  count<T extends OrderDataCountArgs>(
    args?: Prisma.Subset<T, OrderDataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrderDataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrderData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderDataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrderDataAggregateArgs>(args: Prisma.Subset<T, OrderDataAggregateArgs>): Prisma.PrismaPromise<GetOrderDataAggregateType<T>>

  /**
   * Group by OrderData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderDataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrderDataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrderDataGroupByArgs['orderBy'] }
      : { orderBy?: OrderDataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrderDataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrderDataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrderData model
 */
readonly fields: OrderDataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrderData.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrderDataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrderData model
 */
export interface OrderDataFieldRefs {
  readonly id: Prisma.FieldRef<"OrderData", 'Int'>
  readonly date: Prisma.FieldRef<"OrderData", 'DateTime'>
  readonly total: Prisma.FieldRef<"OrderData", 'Int'>
  readonly data: Prisma.FieldRef<"OrderData", 'Json'>
}
    

// Custom InputTypes
/**
 * OrderData findUnique
 */
export type OrderDataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * Filter, which OrderData to fetch.
   */
  where: Prisma.OrderDataWhereUniqueInput
}

/**
 * OrderData findUniqueOrThrow
 */
export type OrderDataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * Filter, which OrderData to fetch.
   */
  where: Prisma.OrderDataWhereUniqueInput
}

/**
 * OrderData findFirst
 */
export type OrderDataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * Filter, which OrderData to fetch.
   */
  where?: Prisma.OrderDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderData to fetch.
   */
  orderBy?: Prisma.OrderDataOrderByWithRelationInput | Prisma.OrderDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrderData.
   */
  cursor?: Prisma.OrderDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrderData.
   */
  distinct?: Prisma.OrderDataScalarFieldEnum | Prisma.OrderDataScalarFieldEnum[]
}

/**
 * OrderData findFirstOrThrow
 */
export type OrderDataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * Filter, which OrderData to fetch.
   */
  where?: Prisma.OrderDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderData to fetch.
   */
  orderBy?: Prisma.OrderDataOrderByWithRelationInput | Prisma.OrderDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrderData.
   */
  cursor?: Prisma.OrderDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrderData.
   */
  distinct?: Prisma.OrderDataScalarFieldEnum | Prisma.OrderDataScalarFieldEnum[]
}

/**
 * OrderData findMany
 */
export type OrderDataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * Filter, which OrderData to fetch.
   */
  where?: Prisma.OrderDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderData to fetch.
   */
  orderBy?: Prisma.OrderDataOrderByWithRelationInput | Prisma.OrderDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrderData.
   */
  cursor?: Prisma.OrderDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderData.
   */
  skip?: number
  distinct?: Prisma.OrderDataScalarFieldEnum | Prisma.OrderDataScalarFieldEnum[]
}

/**
 * OrderData create
 */
export type OrderDataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * The data needed to create a OrderData.
   */
  data: Prisma.XOR<Prisma.OrderDataCreateInput, Prisma.OrderDataUncheckedCreateInput>
}

/**
 * OrderData createMany
 */
export type OrderDataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrderData.
   */
  data: Prisma.OrderDataCreateManyInput | Prisma.OrderDataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrderData createManyAndReturn
 */
export type OrderDataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * The data used to create many OrderData.
   */
  data: Prisma.OrderDataCreateManyInput | Prisma.OrderDataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrderData update
 */
export type OrderDataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * The data needed to update a OrderData.
   */
  data: Prisma.XOR<Prisma.OrderDataUpdateInput, Prisma.OrderDataUncheckedUpdateInput>
  /**
   * Choose, which OrderData to update.
   */
  where: Prisma.OrderDataWhereUniqueInput
}

/**
 * OrderData updateMany
 */
export type OrderDataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrderData.
   */
  data: Prisma.XOR<Prisma.OrderDataUpdateManyMutationInput, Prisma.OrderDataUncheckedUpdateManyInput>
  /**
   * Filter which OrderData to update
   */
  where?: Prisma.OrderDataWhereInput
  /**
   * Limit how many OrderData to update.
   */
  limit?: number
}

/**
 * OrderData updateManyAndReturn
 */
export type OrderDataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * The data used to update OrderData.
   */
  data: Prisma.XOR<Prisma.OrderDataUpdateManyMutationInput, Prisma.OrderDataUncheckedUpdateManyInput>
  /**
   * Filter which OrderData to update
   */
  where?: Prisma.OrderDataWhereInput
  /**
   * Limit how many OrderData to update.
   */
  limit?: number
}

/**
 * OrderData upsert
 */
export type OrderDataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * The filter to search for the OrderData to update in case it exists.
   */
  where: Prisma.OrderDataWhereUniqueInput
  /**
   * In case the OrderData found by the `where` argument doesn't exist, create a new OrderData with this data.
   */
  create: Prisma.XOR<Prisma.OrderDataCreateInput, Prisma.OrderDataUncheckedCreateInput>
  /**
   * In case the OrderData was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrderDataUpdateInput, Prisma.OrderDataUncheckedUpdateInput>
}

/**
 * OrderData delete
 */
export type OrderDataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
  /**
   * Filter which OrderData to delete.
   */
  where: Prisma.OrderDataWhereUniqueInput
}

/**
 * OrderData deleteMany
 */
export type OrderDataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrderData to delete
   */
  where?: Prisma.OrderDataWhereInput
  /**
   * Limit how many OrderData to delete.
   */
  limit?: number
}

/**
 * OrderData without action
 */
export type OrderDataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderData
   */
  select?: Prisma.OrderDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderData
   */
  omit?: Prisma.OrderDataOmit<ExtArgs> | null
}
